@apiUrl = http://127.0.0.1:8080

# Rest-Client kan läsa variabler ur .env
@api_key = {{$dotenv API_KEY2}}

### Get all rooms
GET {{apiUrl}}/rooms


### Get bookings
GET {{apiUrl}}/bookings
X-API-Key: {{api_key}}


### Create booking
POST {{apiUrl}}/bookings
Content-Type: application/json
X-API-Key: {{api_key}}

{
    "room_id": 1,
    "datefrom": "2026-06-01",
    "dateto": "2026-05-03",
    "info": "info0ooo..."
}

### Create Guest
POST {{apiUrl}}/guests
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "user"
}